apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: "ingress-cluster02"
repository: https://kubernetes.github.io/ingress-nginx
chart: ingress-nginx
version: 4.6.1
values:
valueFiles:
  - values.yaml