apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mynamespace

bases:
  - ../../base

resources:
  - resource1.yaml
  - resource2.yaml

patchesStrategicMerge:
  - patch1.yaml