apiVersion: v1
kind: Secret
metadata:
  name: <SECRET_NAME>
  namespace: <NAMESPACE_NAME>
# Secret data with the specification of data are encoded with base64
data:
  username: <BASE64_ENCODED_DATA>
  password: <BASE64_ENCODED_DATA>
type: Opaque
# Secret data with the specification of stringData are unencoded with base64
# stringData:
#   username: <UNENCODED_DATA>
#   password: <UNENCODED_DATA>
