apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
parameters:
  archiveOnDelete: "true"
allowVolumeExpansion: true # enable to allow online volume expansion
mountOptions:
  - nfsvers=3
