apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
  - namespace.yaml
  - https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy/?ref=nfs-subdir-external-provisioner-4.0.18

patchesStrategicMerge:
  - deployment.yaml
  - class.yaml