apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster01

resources:
  - namespace.yaml
  - configmap.yaml
  - certificate.yaml
  - service.yaml
  - postgresql.yaml

generators:
  - generator.yaml

generatorOptions:
  disableNameSuffixHash: true