apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres-cluster01.homelab.thedatabaseme.de"
  name: ingress-postgres-cluster01
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-cluster01
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer